#!/usr/bin/env python3

import os, sys, math

#####################################################

def P(i, iD, A, B, C, X, Y, f):
	return -f[int(i)-1]/30 * (iD-X[int(i)])**3  +  f[int(i)]/30*(iD-X[int(i)-1])**3  -(Y[int(i)-1]/5 - 5/6*f[int(i)-1]) * (iD-X[int(i)])  +  (Y[int(i)]/5 - 5/6*f[int(i)]) * (iD-X[int(i)-1])

#####################################################

def spline(r0, r5, r10, r15, r20, n):
	if (r0 < 0 or r5 < 0 or r10 < 0 or r15 < 0 or r20 < 0 or n < 2):
		exit(84)
	X = [0, 5, 10, 15, 20]
	Y = [r0, r5, r10, r15, r20]
	A = 6 * (r10 - 2 * r5 + r0) / 50
	B = 6 * (r15 - 2 * r10 + r5) / 50
	C = 6 * (r20 - 2 * r15 + r10) / 50
	f = [0, 0, (B -(A + C) / 4) * 4 / 7, 0, 0]
	f[3] = C / 2 - 0.25 * f[2]
	f[1] = A / 2 - 0.25 * f[2]
	print("vector result: [%.1f, %.1f, %.1f, %.1f, %.1f]" %(0 + round(f[0], 1), 0 + round(f[1], 1), 0 + round(f[2], 1), 0 + round(f[3], 1), 0 + round(f[4], 1)))
	for i in range(n-1):
		t = round(20/(n-1)*i, 1)
		print("abscissa: %.1f cm\tradius: %.1f cm" % (t, P(t/5+1, t, A, B, C, X, Y, f)))
	print("abscissa: 20.0 cm\tradius: %.1f cm" % P(4, 20, A, B, C, X, Y, f))
	
#####################################################

if __name__ == '__main__':
	if (len(sys.argv) == 7):
		try:
			spline(float(sys.argv[1]),float(sys.argv[2]),float(sys.argv[3]),float(sys.argv[4]),float(sys.argv[5]),int(sys.argv[6]))
		except:
			exit(84)
	elif (len(sys.argv) == 2):
		if (sys.argv[1] == "-h"):
			print ("USAGE\n\t./308reedpipes r0 r5 r10 r15 r20 n\n\nDESCRIPTION\n\tr0\tradius (in cm) of pipe at the 0cm abscissa\n\tr5\tradius (in cm) of pipe at the 5cm abscissa\n\tr10\tradius (in cm) of pipe at the 10cm abscissa\n\tr15\tradius (in cm) of pipe at the 15cm abscissa\n\tr20\tradius (in cm) of pipe at the 20cm abscissa\n\tn\nnumber of points needed to display the radius")
	else:
		exit(84)
	exit(0)